services:
  front-end:
    build: ./front-end
    ports:
      - "5173:5173"
    networks:
      - catbio-network

  back-end-fasta:
    build: ./back-end-fasta
    ports:
      - "5000:5000"
    networks:
      - catbio-network

networks:
  catbio-network:
    driver: bridge

volumes:
  dbdata: